# Special instructions go here.

# PROJECT
site_name: Material for MkDocs Template Demo
site_author: B.A. Umberger
site_url: https://oldmanumby.github.io/material-for-mkdocs-template
site_description: An demo GitHub template for Material for MkDocs Insiders Edition complete with GH Pages.

# REPOSITORY
repo_name: oldmanumby/material-for-mkdocs-template
repo_url: https://github.com/oldmanumby/material-for-mkdocs-template
edit_uri: edit/main/docs/

# Copyright
copyright: Â© Copyright 2024 by <a href="https://oldmanumby.com" target="_blank" rel="noopener">B.A. Umberger</a>

# CONFIGURATION
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/branding/logo_wht.svg
  favicon: assets/branding/favicon_wht.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
# For custom colors see CSS Overrides below
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - header.autohide
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    #- navigation.expand
    - navigation.path
    #- navigation.prune
    - navigation.top
    - navigation.footer
    #- navigation.indexes
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view

# EXTRA CONFIGURATION
extra:
#  homepage: https://oldmanumby.github.io/material-for-mkdocs-template
  generator: false
  status:
    Add: Recently Added
  social:
    - icon: /fontawesome/regular/envelope
      name: Contact Old Man Umby
      link: mailto:contact@oldmanumby.com
    - icon: fontawesome/brands/github
      name: Old Man Umby on Github
      link: https://github.com/OldManUmby
    - icon: fontawesome/brands/mastodon
      name: Old Man Umby on Mastodon
      link: https://mastodon.social/@oldmanumby
    - icon: fontawesome/brands/x-twitter
      name: Old Man Umby on Twitter
      link: https://twitter.com/oldmanumby

# OVERRIDES
extra_css:
  - _stylesheets/extra.css
extra_javascript:
  - _javascripts/extra.js

# If you're NOT a Material for MkDocs Insider, remove the following plugins.
# Remove: meta, optimize, projects, typset.

# PLUGINS
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
#  - minify:
      minify_html: true
  - meta
  - typeset
  - social
  - blog:
      post_url_format: "{categories}/{slug}"
      archive_date_format: MMM yyyy
      post_excerpt: required
      blog_toc: true
      authors_profiles: true
      pagination_per_page: 10
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - tags:
      tags_file: blog/tags.md
#     comments_path: "#__comments"
# - projects:
#     cache: true

# MARKDOWN
markdown_extensions:
  - admonition
  - md_in_html
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
      permalink: ðŸ”—
      toc_depth: 3
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences

# not_in_nav: |
#  /tutorials/**/*.md

# MENU TREE
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - About: about.md
#  - Getting started:
#    - Installation: getting-started.md
#    - Creating your site: creating-your-site.md
#    - Publishing your site: publishing-your-site.md
#    - Customization: customization.md
#    - Conventions: conventions.md
#    - Browser support: browser-support.md
#    - Enterprise feedback: enterprise-support.md
#    - Philosophy: philosophy.md
#    - Alternatives: alternatives.md
#    - License: license.md
#    - Tutorials:
#      - tutorials/index.md
#      - "Blogs":
#        - tutorials/blogs/basic.md
#        - tutorials/blogs/navigation.md
#        - tutorials/blogs/engage.md
#      - "Social cards":
#        - tutorials/social/basic.md
#        - tutorials/social/custom.md
#    - Changelog:
#      - changelog/index.md
#      - How to upgrade: upgrade.md
#  - Setup:
#    - setup/index.md
#    - Changing the colors: setup/changing-the-colors.md
#    - Changing the fonts: setup/changing-the-fonts.md
#    - Changing the language: setup/changing-the-language.md
#    - Changing the logo and icons: setup/changing-the-logo-and-icons.md
#    - Ensuring data privacy: setup/ensuring-data-privacy.md
#    - Setting up navigation: setup/setting-up-navigation.md
#    - Setting up site search: setup/setting-up-site-search.md
#    - Setting up site analytics: setup/setting-up-site-analytics.md
#    - Setting up social cards: setup/setting-up-social-cards.md
#    - Setting up a blog: setup/setting-up-a-blog.md
#    - Setting up tags: setup/setting-up-tags.md
#    - Setting up versioning: setup/setting-up-versioning.md
#    - Setting up the header: setup/setting-up-the-header.md
#    - Setting up the footer: setup/setting-up-the-footer.md
#    - Adding a git repository: setup/adding-a-git-repository.md
#    - Adding a comment system: setup/adding-a-comment-system.md
#    - Building an optimized site: setup/building-an-optimized-site.md
#    - Building for offline usage: setup/building-for-offline-usage.md
#    - Extensions:
#      - setup/extensions/index.md
#      - Python Markdown: setup/extensions/python-markdown.md
#      - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
#  - Plugins:
#    - plugins/index.md
#    - Blog: plugins/blog.md
#    - Group: plugins/group.md
#    - Info: plugins/info.md
#    - Meta: plugins/meta.md
#    - Offline: plugins/offline.md
#    - Optimize: plugins/optimize.md
#    - Privacy: plugins/privacy.md
#    - Projects: plugins/projects.md
#    - Search: plugins/search.md
#    - Social: plugins/social.md
#    - Tags: plugins/tags.md
#    - Typeset: plugins/typeset.md
#    - Requirements:
#      - Image processing: plugins/requirements/image-processing.md
#      - Caching: plugins/requirements/caching.md
#  - Reference:
#    - reference/index.md
#    - Admonitions: reference/admonitions.md
#    - Annotations: reference/annotations.md
#    - Buttons: reference/buttons.md
#    - Code blocks: reference/code-blocks.md
#    - Content tabs: reference/content-tabs.md
#    - Data tables: reference/data-tables.md
#    - Diagrams: reference/diagrams.md
#    - Footnotes: reference/footnotes.md
#    - Formatting: reference/formatting.md
#    - Grids: reference/grids.md
#    - Icons, Emojis: reference/icons-emojis.md
#    - Images: reference/images.md
#    - Lists: reference/lists.md
#    - Math: reference/math.md
#    - Tooltips: reference/tooltips.md
#  - Insiders:
#    - insiders/index.md
#    - Why sponsor us: insiders/why-sponsor-us.md
#    - What's in it for you: insiders/benefits.md
#    - Who is sponsoring: insiders/our-sponsors.md
#    - Sponsoring tiers: insiders/sponsoring-tiers.md
#    - How to sponsor: insiders/how-to-sponsor.md
#    - Additional information:
#      - Payment and billing: insiders/payment-and-billing.md
#      - Access management: insiders/access-management.md
#      - Runtime and cancellation: insiders/runtime-and-cancellation.md
#      - Privacy: insiders/privacy.md
#      - License: insiders/license.md
#      - Support: support.md
#    - Using Insiders:
#      - Getting started: insiders/getting-started.md
#    - Changelog:
#      - insiders/changelog/index.md
#      - How to upgrade: insiders/upgrade.md
#  - Community:
#    - Contributing:
#      - contributing/index.md
#      - Reporting a bug: contributing/reporting-a-bug.md
#      - Reporting a docs issue: contributing/reporting-a-docs-issue.md
#      - Requesting a change: contributing/requesting-a-change.md
#      - Adding translations: contributing/adding-translations.md
#      - Making a pull request: contributing/making-a-pull-request.md
#      - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
#    - Guides:
#      - Creating a reproduction: guides/creating-a-reproduction.md
#    - Community experts program:
#      - insiders/community-experts-program/index.md